// Every framework event type. Dot-namespaced strings so future consumers
// can pattern-match on prefixes. A const-object union instead of a TS
// enum: Node's type stripping cannot run enums.
export const EventType = {
  AgentCreated: 'agent.created',
  AgentInitialized: 'agent.initialized',
  PlanningStarted: 'planning.started',
  ExecutionStarted: 'execution.started',
  ToolExecutionStarted: 'tool.execution.started',
  ToolExecutionCompleted: 'tool.execution.completed',
  ToolExecutionFailed: 'tool.execution.failed',
  AgentCompleted: 'agent.completed',
  AgentFailed: 'agent.failed',
  AgentCancelled: 'agent.cancelled',
  PluginInstalled: 'plugin.installed',
  PluginUninstalled: 'plugin.uninstalled',
  MessageSent: 'message.sent',
  MessageDelivered: 'message.delivered',
  MessageFailed: 'message.failed',
  TaskCreated: 'task.created',
  TaskAssigned: 'task.assigned',
  TaskStarted: 'task.started',
  TaskCompleted: 'task.completed',
  TaskFailed: 'task.failed',
  TaskCancelled: 'task.cancelled',
  StreamStarted: 'stream.started',
  StreamCompleted: 'stream.completed',
  StreamFailed: 'stream.failed',
  StreamCancelled: 'stream.cancelled',
  InteractionRequested: 'interaction.requested',
  InteractionResolved: 'interaction.resolved',
  InteractionCancelled: 'interaction.cancelled',
  InteractionTimedOut: 'interaction.timedout',
  WorkflowStarted: 'workflow.started',
  WorkflowStepStarted: 'workflow.step.started',
  WorkflowStepCompleted: 'workflow.step.completed',
  WorkflowStepFailed: 'workflow.step.failed',
  WorkflowCompleted: 'workflow.completed',
  WorkflowFailed: 'workflow.failed',
  CheckpointSaved: 'checkpoint.saved',
  CheckpointRecovered: 'checkpoint.recovered',
  CheckpointRecoveryFailed: 'checkpoint.recovery-failed',
  // AAI-039: distributed agent execution lifecycle.
  WorkerRegistered: 'worker.registered',
  WorkerHeartbeat: 'worker.heartbeat',
  WorkerLost: 'worker.lost',
  TaskDelegatedRemote: 'task.delegated.remote',
  TaskRetried: 'task.retried',
} as const;

export type EventType = (typeof EventType)[keyof typeof EventType];
